apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: erda-operator
  name: erda-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erda-operator
  strategy:
    type: {{ .Values.global.updateStrategy.type | default "RollingUpdate" }}
  template:
    metadata:
      labels:
        app: erda-operator
    spec:
      {{- if ne .Values.global.size "demo" }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "dice/platform"
                  operator: Exists
      {{- end }}
      serviceAccountName: erda-operator
      containers:
      - image: {{ .Values.global.image.repository }}/dice-operator:{{ .Values.erda.operator.tag }}
        imagePullPolicy: {{ .Values.global.image.imagePullPolicy }}
        name: erda-operator
        env:
        - name: ETCD_SECRET_NAME
          value: erda-etcd-client-secret
        - name: CRD_KIND_SPECIFIED
          value: Erda
        - name: ENABLE_SPECIFIED_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: ENABLE_CONFIGMAP_NAMESPACE
          value: {{ .Release.Namespace }}
        {{- if .Values.tags.worker }}
        - name: ENABLE_ETCD_SECRET
          value: disable
        {{- end }}
        - name:  INJECT_CLUSTER_INFO
          value: "false"
        - name: ENABLE_AFFINITY
          {{- if ne .Values.global.size "demo" }}
          value: "true"
          {{- else }}
          value: "false"
          {{- end }}
        - name: ERDA_CLUSTER_INFO
          value: dice-cluster-info
        - name: ERDA_ADDON_INFO
          value: dice-addons-info
        {{- with .Values.erda.operator.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      restartPolicy: Always
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
