apiVersion: v2
name: erda-addons
version: 0.1.0
appVersion: 21.04.0
description: An open-source platform bases on Kubernetes that can deploy microservice applications.
keywords:
- Kubernetes
- microservice
- open-source
home: https://www.erda.cloud/
icon: https://github.com/erda-project/erda/raw/develop/docs/files/logo.jpg
sources:
- https://github.com/erda-project/erda
- https://github.com/erda-project/erda-infra
- https://github.com/erda-project/erda-ui
engine: gotpl
type: application
